version: "3"
services:
  prometheus_exporter:
    build: Dockerfile.prometheus
    entrypoint: ./entrypoint.prometheus.sh
    restart: on-failure
  db:
    image: postgres
    restart: on-failure
    volumes:
      - /tmp/insights-compliance-db:/var/lib/postgresql/data:Z
  rails:
    build: .
    restart: on-failure
    entrypoint: ./entrypoint.sh
    ports:
      - '3000:3000'
    volumes:
      - .:/app:Z
    depends_on:
      - db
  racecar:
    build: .
    restart: on-failure
    entrypoint: bash -c 'KAFKAMQ=kafka:29092 bundle exec racecar -l log/racecar.log ComplianceReportsConsumer'
networks:
  default:
    external:
      name: docker_default # should match insights-upload's network name
