#prometheus_exporter_host: localhost
#prometheus_exporter_port: 9394
redis_url: redis:6379
openshift_tokens_secret: MTwXl7kVp4inTho3N6aiw/7fr8iBJv49HwodiPHIdaw=
#OLD# host_inventory_url: https://ci.cloud.paas.upshift.redhat.com
#host_inventory_url: https://insights-inventory-platform-ci.5a9f.insights-dev.openshiftapps.com
host_inventory_url: https://ci.cloud.paas.psi.redhat.com
prometheus_exporter_host: prometheus
prometheus_exporter_port: 9394
